apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: configurator
  name: configurator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: configurator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: configurator
    spec:
      containers:
        - args:
            - "ls -1 apps > sites/apps.txt; \nbench set-config -g db_host $(DB)_HOST; \nbench set-config -gp db_port $(DB)_PORT; \nbench set-config -g redis_cache \"redis://$(REDIS)_CACHE\"; \nbench set-config -g redis_queue \"redis://$(REDIS)_QUEUE\"; \nbench set-config -g redis_socketio \"redis://$(REDIS)_QUEUE\"; \nbench set-config -gp socketio_port $(SOCKETIO)_PORT;\n"
          command:
            - bash
            - -c
          env:
            - name: ADMIN_PASSWORD
              value: admin
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "3306"
            - name: ENCRYPTION_KEY
              value: LmQeNCZFF5hhJw_pi19viiETta2qKHV6YF_Av4nwhqM=
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
            - name: REDIS_CACHE
              value: redis-cache:6379
            - name: REDIS_QUEUE
              value: redis-queue:6379
            - name: SITE_DOMAIN
              value: men.appyinfo.com
            - name: SOCKETIO_PORT
              value: "9000"
          image: frappe-app:latest
          name: configurator
          volumeMounts:
            - mountPath: /home/frappe/frappe-bench/sites
              name: sites-men
      restartPolicy: Always
      volumes:
        - name: sites-men
          persistentVolumeClaim:
            claimName: sites-men
