apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db-data-men
  name: db-data-men
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
