apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - args:
            - nginx-entrypoint.sh
          env:
            - name: ADMIN_PASSWORD
              value: admin
            - name: BACKEND
              value: backend:8000
            - name: CLIENT_MAX_BODY_SIZE
              value: 50m
            - name: ENCRYPTION_KEY
              value: LmQeNCZFF5hhJw_pi19viiETta2qKHV6YF_Av4nwhqM=
            - name: FRAPPE_SITE_NAME_HEADER
              value: $host
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
            - name: PROXY_READ_TIMEOUT
              value: "120"
            - name: SITE_DOMAIN
              value: men.appyinfo.com
            - name: SOCKETIO
              value: websocket:9000
            - name: UPSTREAM_REAL_IP_ADDRESS
              value: 93.190.141.128
            - name: UPSTREAM_REAL_IP_HEADER
              value: X-Forwarded-For
            - name: UPSTREAM_REAL_IP_RECURSIVE
              value: "off"
          image: frappe-app:latest
          name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /home/frappe/frappe-bench/sites
              name: sites-men
      restartPolicy: Always
      volumes:
        - name: sites-men
          persistentVolumeClaim:
            claimName: sites-men
