apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: queue-long
  name: queue-long
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: queue-long
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: queue-long
    spec:
      containers:
        - args:
            - bench
            - worker
            - --queue
            - long,default,short
          env:
            - name: ADMIN_PASSWORD
              value: admin
            - name: ENCRYPTION_KEY
              value: LmQeNCZFF5hhJw_pi19viiETta2qKHV6YF_Av4nwhqM=
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
            - name: SITE_DOMAIN
              value: men.appyinfo.com
          image: frappe-app:latest
          name: queue-long
          volumeMounts:
            - mountPath: /home/frappe/frappe-bench/sites
              name: sites-men
      restartPolicy: Always
      volumes:
        - name: sites-men
          persistentVolumeClaim:
            claimName: sites-men
