apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis-queue
  name: redis-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-queue
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: redis-queue
    spec:
      containers:
        - image: redis:6.2-alpine
          name: redis-queue
          volumeMounts:
            - mountPath: /data
              name: redis-queue-data-men
      restartPolicy: Always
      volumes:
        - name: redis-queue-data-men
          persistentVolumeClaim:
            claimName: redis-queue-data-men
