apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: redis-cache-data-men
  name: redis-cache-data-men
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
