apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sites-men
  name: sites-men
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
