apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-men
  namespace: zatca-men
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual  # تأكد أن StorageClass مطابق لـ PV
  volumeName: db-data-men-pv  # ربطه مباشرة بـ PV
