apiVersion: v1
kind: PersistentVolume
metadata:
  name: sites-men-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/sites-men"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-men-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/db-data-men"
