name: zatca
services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe-app:latest
    networks:
      - appy
    platform: linux/amd64
    # pull_policy: always
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: apps
        target: /home/frappe/frappe-bench/apps
        volume: {}
    environment:
      ENCRYPTION_KEY: "LmQeNCZFF5hhJw_pi19viiETta2qKHV6YF_Av4nwhqM="
      MYSQL_ROOT_PASSWORD: "123"
      ADMIN_PASSWORD: "admin"
      SITE_DOMAIN: "localhost"

  configurator:
    command:
      - |
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
        bench pip install python-dotenv;
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
    entrypoint:
      - bash
      - -c
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
      ENCRYPTION_KEY: "LmQeNCZFF5hhJw_pi19viiETta2qKHV6YF_Av4nwhqM="
      MYSQL_ROOT_PASSWORD: "123"
      ADMIN_PASSWORD: "admin"
      SITE_DOMAIN: "localhost"
    image: frappe-app:latest
    networks:
      - appy
    platform: linux/amd64
    # pull_policy: always
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: apps
        target: /home/frappe/frappe-bench/apps
        volume: {}

  db:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost --password=123
      interval: 1s
      retries: 15
    image: mariadb:10.6
    networks:
      - appy
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
        volume: {}

  frontend:
    image: frappe-app:latest
    command:
      - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      ENCRYPTION_KEY: "LmQeNCZFF5hhJw_pi19viiETta2qKHV6YF_Av4nwhqM="
      MYSQL_ROOT_PASSWORD: "123"
      ADMIN_PASSWORD: "admin"
      SITE_DOMAIN: "localhost"
    networks:
      - appy
    platform: linux/amd64
    # pull_policy: always
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: apps
        target: /home/frappe/frappe-bench/apps
        volume: {}
    ports:
      - "8080:8080"

  queue-long:
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe-app:latest
    networks:
      - appy
    platform: linux/amd64
    # pull_policy: always
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: apps
        target: /home/frappe/frappe-bench/apps
        volume: {}
    environment:
      ENCRYPTION_KEY: "LmQeNCZFF5hhJw_pi19viiETta2qKHV6YF_Av4nwhqM="
      MYSQL_ROOT_PASSWORD: "123"
      ADMIN_PASSWORD: "admin"
      SITE_DOMAIN: "localhost"

  queue-short:
    command:
      - bench
      - worker
      - --queue
      - short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe-app:latest
    networks:
      - appy
    platform: linux/amd64
    # pull_policy: always
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: apps
        target: /home/frappe/frappe-bench/apps
        volume: {}
    environment:
      ENCRYPTION_KEY: "LmQeNCZFF5hhJw_pi19viiETta2qKHV6YF_Av4nwhqM="
      MYSQL_ROOT_PASSWORD: "123"
      ADMIN_PASSWORD: "admin"
      SITE_DOMAIN: "localhost"

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - appy
    volumes:
      - type: volume
        source: redis-cache-data
        target: /data
        volume: {}

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - appy
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}

  scheduler:
    command:
      - bench
      - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe-app:latest
    networks:
      - appy
    platform: linux/amd64
    # pull_policy: always
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: apps
        target: /home/frappe/frappe-bench/apps
        volume: {}
    environment:
      ENCRYPTION_KEY: "LmQeNCZFF5hhJw_pi19viiETta2qKHV6YF_Av4nwhqM="
      MYSQL_ROOT_PASSWORD: "123"
      ADMIN_PASSWORD: "admin"
      SITE_DOMAIN: "localhost"

  websocket:
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe-app:latest
    networks:
      - appy
    platform: linux/amd64
    # pull_policy: always
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: apps
        target: /home/frappe/frappe-bench/apps
        volume: {}
    environment:
      ENCRYPTION_KEY: "LmQeNCZFF5hhJw_pi19viiETta2qKHV6YF_Av4nwhqM="
      MYSQL_ROOT_PASSWORD: "123"
      ADMIN_PASSWORD: "admin"
      SITE_DOMAIN: "localhost"

networks:
    appy:
      driver: bridge

volumes:
  cert-data:
    name: appyerp_cert-data
  db-data:
    name: appyerp_db-data
  redis-cache-data:
    name: appyerp_redis-cache-data
  redis-queue-data:
    name: appyerp_redis-queue-data
  sites:
    name: appyerp_sites
  apps:
    name: appyerp_apps

x-backend-defaults:
  depends_on:
    configurator:
      condition: service_completed_successfully
  image: frappe-app:latest
  # pull_policy: always
  volumes:
    - sites:/home/frappe/frappe-bench/sites
    - apps:/home/frappe/frappe-bench/apps

x-customizable-image:
  image: frappe-app:latest
  # pull_policy: always

x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
