apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: erpnext
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: test.men.appyinfo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frappe-bench-erpnext
            port:
              number: 8080
